### ISSUE TITLE
Repeat n Times tile in Kedama broken

### ISSUE THREAD

**Issue by JensLincke** [timfel/etoys-spur#1]
first error: block accepts one parameter but was called with none...

after clicking debuggers away... I got into the emergency evaluator

**Comment by JensLincke** [comment]
<img width="424" alt="repeatntimesbroken" src="https://cloud.githubusercontent.com/assets/1466247/17808571/0e8b0250-6611-11e6-9bdd-97e8dca92a83.PNG">

**Comment by JensLincke** [comment]
<img width="806" alt="kedamaemergencyevaluator" src="https://cloud.githubusercontent.com/assets/1466247/17808574/127b7156-6611-11e6-8e11-8d6c62177eaa.PNG">

**Comment by timfel** [comment]
Fixed
