### ISSUE TITLE
etoys script "test tile" is stripped from while saving

### ISSUE THREAD

**Issue by JensLincke** [timfel/etoys-spur#13]
<img width="524" alt="squeaketoysscriptsourcechangedonsavingafter" src="https://cloud.githubusercontent.com/assets/1466247/17810843/c8c8ade4-661f-11e6-9d61-137d57106e11.PNG">
<img width="523" alt="squeaketoysscriptsourcechangedonsavingbefore" src="https://cloud.githubusercontent.com/assets/1466247/17810842/c8c88c1a-661f-11e6-8280-e56b897f920a.PNG">

**Comment by timfel** [comment]
Should be fixed
