### ISSUE TITLE
Kedama randomness is the same for all particle instances

### ISSUE THREAD

**Issue by JensLincke** [timfel/etoys-spur#18]
This is not what I expected. 

Random number and color should be random for every particle.

**Comment by JensLincke** [comment]
https://www.dropbox.com/s/cqvvoix6svduafq/Kedama%20Random%20is%20not%20Random.mp4?dl=0

**Comment by JensLincke** [comment]
As the video shows: the randomness works for the rotation, but not for the "Test" tile. It seems that the dice is only thrown for onces and the result is applied for all particles.

**Comment by timfel** [comment]
Fixed
