### ISSUE TITLE
when endlessly creating to many kedma turtles the image hangs

### ISSUE THREAD

**Issue by JensLincke** [timfel/etoys-spur#19]
Alt+. does also not seem to work anymore then. (experienced in the non etoys friendly mode... if this makes any difference)

**Comment by JensLincke** [comment]
The squeak vm did not consume any CPU

**Comment by JensLincke** [comment]
I had to use the task manager to kill it, not even the task bar and close window worked.

**Comment by JensLincke** [comment]
Found the bug! Due to the changed implementation of semaphores in squeak there was a deadlock between drawing code and model update code in kedama.

We fixed this my replacing `critical:` with `critical: ifLocked:` and do nothing.

``` Smalltalk
KedamaMorph>>#drawTurtlesOnForm: aForm

    turtlesToDisplay do: [:exampler |
        (self isVisible: exampler) ifTrue: [
            turtlesDictSemaphore critical: [
                exampler turtles drawOn: aForm.
            ] ifLocked: [

            ]
        ].
    ].
```

**Comment by JensLincke** [comment]
@marceltaeumel helped me find and fix it

**Comment by timfel** [comment]
I applied this fix in trunk
