### ISSUE TITLE
"Programtext zeigen" in the script menu is broken

### ISSUE THREAD

**Issue by JensLincke** [timfel/etoys-spur#6]

**Comment by timfel** [comment]
That's when you tried it in a kedama turtle script, right?

**Comment by JensLincke** [comment]
Yes, it is broken only in kedama

**Comment by timfel** [comment]
Ok, I tried this and it actually is only broken when you use the script from the KedamaTurtle itself. If you put the kedama turtle tiles in a script on the kedama world, then it appears to work correctly. The problem is a decompiler bug that I'm looking at now.

**Comment by timfel** [comment]
Should be fixed
